### PR TITLE
add tcb_unbind_notification invocation

### PR DESCRIPTION
**Pull request by alwin-joshy**

### CODE REVIEW

**Comment by alwin-joshy** [comment]
Not sure why this failed the build check. The log isn't showing anything and it works locally

**Comment by nspin** [comment]
Thanks for this!

I've seen spurious errors like this before where the logs aren't available. Not sure what happened, but I just re-ran the job and it passed.

Would you mind turning this PR into one linear commit? At least for now, we are trying to maintain a linear commit history.

**Comment by alwin-joshy** [comment]
Done, sorry. Accidentally synced with main using merge instead of rebase

**Comment by nspin** [comment]
That CI failure where the logs disappear happened again. Weird. I’ll investigate

**Pull request merged**
